# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      # Build with env variables injected (CRA needs REACT_APP_* at build time)
      - name: Build
        run: npm run build
        env:
          CI: false
          REACT_APP_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          REACT_APP_SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          REACT_APP_SUPABASE_DB:  ${{ vars.SUPABASE_DB || 'itsscanning' }}
          PUBLIC_URL: https://mkd5152.github.io/project-istiqbaal

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
